#  cloud:
#    gateway:
#      routes:
#        - id: productModule
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/product-service/api/products/**
#          filters:
#            - APIGatewayFilter
          #      - id: userModule
          #        uri: http://localhost:8081/
          #        predicates:
          #        - Path=/users/**
spring:
  application:
    name: ${SERVER_NAME:gateway-service}
server:
  port: 8888

eureka:
  instance:
    hostname: ${HOST:localhost}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
