spring:
  application:
    name: ${SERVER_NAME:notification-service}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest

server:
  port: 8081
  servlet:
    context-path: /notification-service

eureka:
  instance:
    hostname: ${HOST:localhost}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka